stages:
  - convert
  - test
  - build_website
  - dockerize
  - openshift_redeploy

include:
  - local: 'alice-masterclass-django/.gitlab-ci.yml'
  - local: 'alice-masterclass-js/.gitlab-ci.yml'
  - local: 'alice-masterclass-teacher/.gitlab-ci.yml'
