apiVersion: v1
kind: List
items:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: alice-masterclass-demo
      namespace: alice-web-masterclass-demo
      labels:
        app: alice-masterclass-demo
        app.kubernetes.io/component: alice-masterclass-demo
        app.kubernetes.io/instance: alice-masterclass-demo
        app.kubernetes.io/part-of: alice-masterclass-demo
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: alice-masterclass-demo
        deploymentconfig: alice-masterclass-demo
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: alice-masterclass-demo
            deploymentconfig: alice-masterclass-demo
        spec:
          containers:
            - name: alice-masterclass-demo
              image: image-registry.openshift-image-registry.svc:5000/alice-web-masterclass-demo/alice-masterclass-demo:latest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - alice-masterclass-demo
            from:
              kind: ImageStreamTag
              name: alice-masterclass-demo:latest
              namespace: alice-web-masterclass-demo
        - type: ConfigChange