apiVersion: v1
kind: List
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: alice-masterclass
      namespace: alice-web-masterclass-dev
      labels:
        app: alice-masterclass
        app.kubernetes.io/component: alice-masterclass
        app.kubernetes.io/instance: alice-masterclass
        app.kubernetes.io/part-of: alice-masterclass
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: gitlab-registry.cern.ch/alice-masterclass-dev-group/alice-masterclass-dev/alice-masterclass:latest
          importPolicy:
            importMode: Legacy
          referencePolicy:
            type: Local
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: alice-masterclass-django
      namespace: alice-web-masterclass-dev
      labels:
        app: alice-masterclass-django
        app.kubernetes.io/component: alice-masterclass-django
        app.kubernetes.io/instance: alice-masterclass-django
        app.kubernetes.io/part-of: alice-masterclass-django
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: gitlab-registry.cern.ch/alice-masterclass-dev-group/alice-masterclass-dev/alice-masterclass-django:latest
          importPolicy:
            importMode: Legacy
          referencePolicy:
            type: Local
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: alice-masterclass-teacher
      namespace: alice-web-masterclass-dev
      labels:
        app: alice-masterclass-teacher
        app.kubernetes.io/component: alice-masterclass-teacher
        app.kubernetes.io/instance: alice-masterclass-teacher
        app.kubernetes.io/part-of: alice-masterclass-teacher
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: gitlab-registry.cern.ch/alice-masterclass-dev-group/alice-masterclass-dev/alice-masterclass-teacher:latest
          importPolicy:
            importMode: Legacy
          referencePolicy:
            type: Local
