# Generated by Django 5.2.12 on 2026-08-19 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterclass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventExplorationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.PositiveIntegerField()),
                ('dataset', models.IntegerField(default=0)),
                ('ppEvents', models.PositiveIntegerField(default=0)),
                ('meanPpMultiplicity', models.FloatField(default=0.0)),
                ('meanPpMultiplicityMinPt', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclass.session')),
            ],
        ),
        migrations.CreateModel(
            name='EventExplorationResultsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventClass', models.CharField(choices=[('pp7TeV', 'pp 7 TeV (no field)'), ('pp276TeV', 'pp 2.76 TeV'), ('pbPbPeripheral', 'Pb-Pb peripheral'), ('pbPbSemiCentral', 'Pb-Pb semi-central'), ('pbPbCentral', 'Pb-Pb central')], max_length=16)),
                ('nColl', models.FloatField()),
                ('multiplicity', models.PositiveIntegerField()),
                ('multiplicityMinPt', models.PositiveIntegerField()),
                ('raa', models.FloatField()),
                ('raaMinPt', models.FloatField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuclear_modification.eventexplorationresult')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventexplorationresult',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='eer_u_fields'),
        ),
        migrations.AddConstraint(
            model_name='eventexplorationresultsentry',
            constraint=models.UniqueConstraint(fields=('result', 'eventClass'), name='eere_u_fields'),
        ),
    ]
