import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, map, shareReplay } from 'rxjs';

import { Event } from '../shared/models';
import { RaaMetadata } from '../shared/models/raa/raa';
import {
  RaaEventsAsset,
  RaaPpAsset,
  RaaTracksDemoAsset,
  RaaTracksFineAsset,
} from '../shared/models/raa/spectrum';
import { withResolvedTrackSigns } from '../shared/utils/track-charge';

@Injectable({
  providedIn: 'root',
})
export class RaaDataService {
  readonly DATA_PATH = 'assets/exercises/raa';

  /** Spectrum Analysis assets, generated by `data/raa/part2/build_assets.py`. */
  readonly PART2_PATH = 'assets/exercises/raa/part2';

  private metadata$?: Observable<RaaMetadata>;
  private tracksFine$?: Observable<RaaTracksFineAsset>;
  private events$?: Observable<RaaEventsAsset>;
  private pp$?: Observable<RaaPpAsset>;
  private tracksDemo$?: Observable<RaaTracksDemoAsset>;

  constructor(private readonly http: HttpClient) {}

  getMetadata(): Observable<RaaMetadata> {
    if (!this.metadata$) {
      this.metadata$ = this.http
        .get<RaaMetadata>(`${this.DATA_PATH}/metadata.json`)
        .pipe(shareReplay(1));
    }
    return this.metadata$;
  }

  /** Lossless 0.01 GeV/c track tally per centrality class. */
  getTracksFine(): Observable<RaaTracksFineAsset> {
    if (!this.tracksFine$) {
      this.tracksFine$ = this.http
        .get<RaaTracksFineAsset>(`${this.PART2_PATH}/tracks_fine.json`)
        .pipe(shareReplay(1));
    }
    return this.tracksFine$;
  }

  /** Multiplicity and centrality of every event in the sample. */
  getEvents(): Observable<RaaEventsAsset> {
    if (!this.events$) {
      this.events$ = this.http
        .get<RaaEventsAsset>(`${this.PART2_PATH}/events.json`)
        .pipe(shareReplay(1));
    }
    return this.events$;
  }

  /** pp dN/dp_T per event — already normalised, so never divide it again. */
  getPpReference(): Observable<RaaPpAsset> {
    if (!this.pp$) {
      this.pp$ = this.http
        .get<RaaPpAsset>(`${this.PART2_PATH}/pp_reference.json`)
        .pipe(shareReplay(1));
    }
    return this.pp$;
  }

  /** A few thousand real tracks, used only by the tutorial demonstration. */
  getTracksDemo(): Observable<RaaTracksDemoAsset> {
    if (!this.tracksDemo$) {
      this.tracksDemo$ = this.http
        .get<RaaTracksDemoAsset>(`${this.PART2_PATH}/tracks_demo.json`)
        .pipe(shareReplay(1));
    }
    return this.tracksDemo$;
  }

  getShowcaseEvent(relativeFile: string): Observable<Event> {
    return this.http
      .get<Event>(`${this.DATA_PATH}/${relativeFile}`)
      .pipe(map((ev) => withResolvedTrackSigns(ev)));
  }

  /** Loads one real event from a real dataset, converted from the desktop app's VSD ROOT files. */
  getDatasetEvent(datasetId: number, eventNumber: number): Observable<Event> {
    return this.http
      .get<Event>(`${this.DATA_PATH}/datasets/event_${datasetId}_${eventNumber}.json`)
      .pipe(map((ev) => withResolvedTrackSigns(ev)));
  }
}
