unit_tests_teacher:
  stage: test
  image: timbru31/node-chrome:fermium
  before_script:
    - cd "$CI_PROJECT_DIR/alice-masterclass-teacher"
    - npm install -g @angular/cli
    - npm install -g npm@latest
  script:
    - npm ci
    - npm run build
    - npm run test:ci

build_website_teacher:
  stage: build
  only:
    - tags
  except:
    - branches
  image: node:22-bookworm
  before_script:
    - cd "$CI_PROJECT_DIR/alice-masterclass-teacher"
    - npm install -g npm@11
  script:
    - npm ci
    - export VERSION=$CI_COMMIT_TAG
    - node -p "let data = require('./package.json'); data.version='$VERSION'; JSON.stringify(data, null, 2)" > package_version.json
    - mv package_version.json package.json
    - npm run build
    - cp .htaccess ./dist/
  artifacts:
    paths:
      - alice-masterclass-teacher/dist/

build_docker_teacher:
  stage: dockerize
  only:
    - tags
  except:
    - branches
  needs:
    - job: build_website_teacher
      artifacts: true
  tags:
    - docker-privileged-xl
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
      DOCKER_TLS_CERTDIR: "/certs"
      CONTAINER_VERSION_IMAGE: $CI_REGISTRY_IMAGE/alice-masterclass-teacher:$CI_COMMIT_TAG
      CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE/alice-masterclass-teacher:latest
  before_script:
   - docker info
   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
   - docker build --pull -f alice-masterclass-teacher/Dockerfile -t $CONTAINER_VERSION_IMAGE alice-masterclass-teacher
   - docker push $CONTAINER_VERSION_IMAGE
   - docker tag $CONTAINER_VERSION_IMAGE $CONTAINER_LATEST_IMAGE
   - docker push $CONTAINER_LATEST_IMAGE

redeploy_teacher:
  stage: openshift_redeploy
  only:
    - tags
  except:
    - branches
  needs:
    - job: build_docker_teacher
      artifacts: false
  image: gitlab-registry.cern.ch/paas-tools/openshift-client:latest
  environment:
    name: dev
    url: https://alice-web-masterclass-dev.app.cern.ch/
  script:
    - "oc import-image $APP_NAME --all --server=$SERVER --namespace $NAMESPACE --token=$IMAGE_IMPORT_TOKEN"
    - "sleep 30s && oc rollout status dc/$APP_NAME --server=$SERVER --namespace $NAMESPACE --token=$IMAGE_IMPORT_TOKEN"
  variables:
    SERVER: https://api.paas.okd.cern.ch
    APP_NAME: alice-masterclass-teacher
